"""Argument-type extraction from routine DDL bodies (Phase 16.9).

Codebases generated by older tool versions (or via ``yaml apply``) carry
autodoc headers without ``object_signature`` / ``argument_types`` — the
resulting ``object_key`` has no ``/signature/<hash>`` suffix, while a fresh
reverse-engineer always writes one. The comparator then splits the very same
function into an added+removed pair (67 functions on cis_zup, 2026-09-14).

This module derives the catalog-compatible ``argument_types`` string from the
``CREATE [OR REPLACE] FUNCTION|PROCEDURE`` header in the SQL body, so the
parser can reconstruct the missing signature and merge identities. The
canonicalization targets ``pg_type.typname`` form (``int4``/``varchar``/
``bool`` — see :mod:`db_project_manager.domain.signature`), NOT the DDL
spelling the body is written in (``integer``/``character varying``/``boolean``).

Deliberately regex-based, not sqlglot-AST: GP function DDL may end with
``EXECUTE ON ANY`` (unparseable by sqlglot → Command node, LESSONS §72-1) and
the header regex is stable regardless of body language/dialect.
"""

from __future__ import annotations

import re

#: ``CREATE [OR REPLACE] FUNCTION|PROCEDURE <qualified name> ( <args> )`` —
#: captures the balanced argument list (args may contain nested parens in
#: type modifiers like numeric(10,2)).
_ROUTINE_HEADER_RE = re.compile(
    r"\bcreate\s+(?:or\s+replace\s+)?(?:function|procedure)\s+"
    r'(?:"?(?:""|[^".()])+\"?\.)?"?(?:""|[^".()])+\"?\s*\(',
    re.IGNORECASE,
)

#: Parameter mode markers (PG proargtypes keeps IN/INOUT/VARIADIC, drops OUT).
_MODE_RE = re.compile(r"^\s*(inout|in|out|variadic)\s+", re.IGNORECASE)

#: ``DEFAULT <expr>`` tail of a parameter (expr runs to the top-level comma).
_DEFAULT_SPLIT_RE = re.compile(r"\s+default\s+", re.IGNORECASE)

#: DDL spelling → pg_type.typname. Only the forms pg_get_functiondef can emit.
_DDL_TO_TYPNAME = {
    "smallint": "int2",
    "int": "int4",
    "integer": "int4",
    "int4": "int4",
    "serial": "int4",
    "bigint": "int8",
    "int8": "int8",
    "bigserial": "int8",
    "real": "float4",
    "float4": "float4",
    "double precision": "float8",
    "float8": "float8",
    "character varying": "varchar",
    "varchar": "varchar",
    "character": "bpchar",
    "char": "bpchar",
    "bpchar": "bpchar",
    "boolean": "bool",
    "bool": "bool",
    "timestamp without time zone": "timestamp",
    "timestamp": "timestamp",
    "timestamp with time zone": "timestamptz",
    "timestamptz": "timestamptz",
    "time without time zone": "time",
    "time": "time",
    "time with time zone": "timetz",
    "timetz": "timetz",
    "decimal": "numeric",
    "numeric": "numeric",
    "text": "text",
    "bytea": "bytea",
    "date": "date",
    "interval": "interval",
    "json": "json",
    "jsonb": "jsonb",
    "uuid": "uuid",
    "xml": "xml",
    "money": "money",
}


def extract_argument_types(body: str) -> str:
    """Catalog-compatible argument type list from a routine DDL body.

    Returns the typname-form comma-separated string (``"json"``,
    ``"text,varchar"``) — the same shape the adapter produces via
    ``pg_type.typname`` — or ``""`` when the header or the arguments cannot
    be determined (no-arg routines also yield ``""``: the empty signature
    never gets a ``/signature/`` suffix, by design).
    """
    match = _ROUTINE_HEADER_RE.search(body)
    if not match:
        return ""
    args_text = _balanced_parens_body(body, match.end() - 1)
    if args_text is None:
        return ""

    types: list[str] = []
    for param in _split_top_level_commas(args_text):
        kind = _param_type(param)
        if kind is None:  # OUT parameter — excluded from proargtypes
            continue
        if kind:
            types.append(kind)
    return ",".join(types)


def _balanced_parens_body(text: str, open_idx: int) -> str | None:
    """Content between the paren at ``open_idx`` and its balanced close."""
    depth = 0
    in_quote: str | None = None
    i = open_idx
    while i < len(text):
        ch = text[i]
        if in_quote:
            if ch == in_quote:
                if i + 1 < len(text) and text[i + 1] == in_quote:  # '' escape
                    i += 2
                    continue
                in_quote = None
            i += 1
            continue
        if ch in ("'", '"'):
            in_quote = ch
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return text[open_idx + 1 : i]
        i += 1
    return None


def _split_top_level_commas(text: str) -> list[str]:
    """Split by commas outside quotes/parens (types contain ``(10,2)``)."""
    items: list[str] = []
    buf: list[str] = []
    depth = 0
    in_quote: str | None = None
    i, n = 0, len(text)
    while i < n:
        ch = text[i]
        if in_quote:
            buf.append(ch)
            if ch == in_quote:
                if i + 1 < n and text[i + 1] == in_quote:
                    buf.append(text[i + 1])
                    i += 2
                    continue
                in_quote = None
            i += 1
            continue
        if ch in ("'", '"'):
            in_quote = ch
            buf.append(ch)
        elif ch == "(":
            depth += 1
            buf.append(ch)
        elif ch == ")":
            depth = max(0, depth - 1)
            buf.append(ch)
        elif ch == "," and depth == 0:
            items.append("".join(buf))
            buf = []
        else:
            buf.append(ch)
        i += 1
    items.append("".join(buf))
    return items


def _param_type(param: str) -> str | None:
    """Typname form of one parameter; ``None`` for OUT params (dropped)."""
    param = param.strip()
    if not param:
        return ""
    mode = _MODE_RE.match(param)
    if mode and mode.group(1).lower() == "out":
        return None
    if mode:
        param = param[mode.end() :]
    # Drop ``DEFAULT <expr>`` — proargtypes carries types only.
    param = _DEFAULT_SPLIT_RE.split(param, maxsplit=1)[0].strip()
    if not param:
        return ""
    # ``name type`` → keep everything after the FIRST token (the name);
    # a bare type (no name) stays whole. ``%TYPE`` anchors are stripped.
    tokens = param.split()
    kind = " ".join(tokens[1:]) if len(tokens) > 1 else tokens[0]
    kind = kind.split("%")[0].strip()
    return _to_typname(kind)


def _to_typname(kind: str) -> str:
    """DDL spelling → pg_type.typname (lowercase, alias-folded)."""
    kind = kind.strip().lower()
    # Array types: pg_type names them ``_text`` / ``_int4``.
    if kind.endswith("[]"):
        return "_" + _to_typname(kind[:-2])
    # Schema-qualified user types: typname is the bare (last) component.
    if "." in kind:
        kind = kind.rsplit(".", 1)[1]
    # Type modifiers (``numeric(10,2)``, ``varchar(255)``): typname carries
    # none, and canonical_signature strips them anyway — drop for symmetry.
    if "(" in kind and kind.endswith(")"):
        kind = kind.split("(", 1)[0].strip()
    return _DDL_TO_TYPNAME.get(kind, kind)
